import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <main className="flex h-screen w-screen flex-col items-center bg-red-900 text-red-50">
          <div className="aspect-[3/2] max-h-full max-w-full flex-1 p-4">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
