import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import Background from "./components/Background";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable} text-[min(3vh,2.25vw)]`}>
      <body>
        <main className="h-screen snap-y snap-mandatory items-center overflow-y-scroll bg-black text-red-50">
          <Suspense>
            <Background />
          </Suspense>
          {children}
        </main>
      </body>
    </html>
  );
}
